/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButton {
        "block": boolean;
        "disabled": boolean;
        "linkUrl": string;
        "loading": boolean;
        "onClick": Function;
        "target": string;
        "text": string;
        "type": 'default' | 'primary' | 'link' | 'text' | 'dashed';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyIcon {
        "class": string;
        "color": string;
        "name": string;
        "size": string;
    }
    interface MyInput {
        "defaultValue": string | number;
        "hasBorder": boolean;
        "placeholder": string;
        "type": 'text' | 'textarea' | 'color' | 'checkbox' | 'date' | 'file';
        "value": string | number;
    }
    interface MyModal {
        "close"?: boolean;
        "footerclass"?: string;
        "headerTitle"?: string;
        "headerclass"?: string;
        "onCancel"?: Function;
        "onOk"?: (v:Object) => void;
        "visible": boolean;
    }
    interface MyPopover {
        "position"?: 't' | 'b' | 'l' | 'r' | 'tl' | 'tr' | 'bl' | 'br';
        "target"?: 'hover' | 'click';
        "visible"?: boolean;
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyIconElement extends Components.MyIcon, HTMLStencilElement {
    }
    var HTMLMyIconElement: {
        prototype: HTMLMyIconElement;
        new (): HTMLMyIconElement;
    };
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {
    }
    var HTMLMyModalElement: {
        prototype: HTMLMyModalElement;
        new (): HTMLMyModalElement;
    };
    interface HTMLMyPopoverElement extends Components.MyPopover, HTMLStencilElement {
    }
    var HTMLMyPopoverElement: {
        prototype: HTMLMyPopoverElement;
        new (): HTMLMyPopoverElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-component": HTMLMyComponentElement;
        "my-icon": HTMLMyIconElement;
        "my-input": HTMLMyInputElement;
        "my-modal": HTMLMyModalElement;
        "my-popover": HTMLMyPopoverElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "block"?: boolean;
        "disabled"?: boolean;
        "linkUrl"?: string;
        "loading"?: boolean;
        "onClick"?: Function;
        "target"?: string;
        "text"?: string;
        "type"?: 'default' | 'primary' | 'link' | 'text' | 'dashed';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyIcon {
        "class"?: string;
        "color"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface MyInput {
        "defaultValue"?: string | number;
        "hasBorder"?: boolean;
        "placeholder"?: string;
        "type"?: 'text' | 'textarea' | 'color' | 'checkbox' | 'date' | 'file';
        "value"?: string | number;
    }
    interface MyModal {
        "close"?: boolean;
        "footerclass"?: string;
        "headerTitle"?: string;
        "headerclass"?: string;
        "onCancel"?: Function;
        "onOk"?: (v:Object) => void;
        "visible"?: boolean;
    }
    interface MyPopover {
        "position"?: 't' | 'b' | 'l' | 'r' | 'tl' | 'tr' | 'bl' | 'br';
        "target"?: 'hover' | 'click';
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-component": MyComponent;
        "my-icon": MyIcon;
        "my-input": MyInput;
        "my-modal": MyModal;
        "my-popover": MyPopover;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-icon": LocalJSX.MyIcon & JSXBase.HTMLAttributes<HTMLMyIconElement>;
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-modal": LocalJSX.MyModal & JSXBase.HTMLAttributes<HTMLMyModalElement>;
            "my-popover": LocalJSX.MyPopover & JSXBase.HTMLAttributes<HTMLMyPopoverElement>;
        }
    }
}
